// <auto-generated />
using System;
using ConsultancyApp.Data.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultancyApp.Data.Migrations
{
    [DbContext(typeof(ConsultancyAppContext))]
    partial class ConsultancyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("AgenciesCategory", b =>
                {
                    b.Property<int>("AgenciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgenciesId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AgenciesCategory");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Agencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoundationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "bu bir frontend firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(1977),
                            FoundationYear = 2000,
                            ImageUrl = "mellon-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(1989),
                            Name = "Mellon",
                            Price = 150.0,
                            Url = "mellon-egitim-kurumu"
                        },
                        new
                        {
                            Id = 2,
                            About = "bu bir backend egitimi veren  firmadır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(1996),
                            FoundationYear = 2000,
                            ImageUrl = "ferisoft-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(1997),
                            Name = "Ferisoft",
                            Price = 150.0,
                            Url = "ferisoft-egitim-kurumu"
                        },
                        new
                        {
                            Id = 3,
                            About = "bu bir veri tabanı firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2000),
                            FoundationYear = 2000,
                            ImageUrl = "evkal-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2000),
                            Name = "Evkal",
                            Price = 150.0,
                            Url = "evkal-egitim-kurumu"
                        },
                        new
                        {
                            Id = 4,
                            About = "bu bir Android programlama firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2003),
                            FoundationYear = 2000,
                            ImageUrl = "appricot-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2004),
                            Name = "Appricot",
                            Price = 150.0,
                            Url = "appricot-egitim-kurumu"
                        },
                        new
                        {
                            Id = 5,
                            About = "bu bir IOS ve bulut bilişim egitim firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2006),
                            FoundationYear = 2000,
                            ImageUrl = "appwox-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2007),
                            Name = "Appwox",
                            Price = 150.0,
                            Url = "appwox-egitim-kurumu"
                        },
                        new
                        {
                            Id = 6,
                            About = "bu bir Cybersecurity firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2009),
                            FoundationYear = 2000,
                            ImageUrl = "taze-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2010),
                            Name = "Taze",
                            Price = 150.0,
                            Url = "taze-egitim-kurumu"
                        },
                        new
                        {
                            Id = 7,
                            About = "bu bir Tasarım firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2013),
                            FoundationYear = 2000,
                            ImageUrl = "house-of-apps-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2013),
                            Name = "House Of Apps",
                            Price = 150.0,
                            Url = "house-of-apps-egitim-kurumu"
                        },
                        new
                        {
                            Id = 8,
                            About = "bu bir web application egitim firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2016),
                            FoundationYear = 2000,
                            ImageUrl = "westerops-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2017),
                            Name = "Westerops",
                            Price = 150.0,
                            Url = "westerops-egitim-kurumu"
                        },
                        new
                        {
                            Id = 9,
                            About = "bu bir oyun programlama firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2019),
                            FoundationYear = 2002,
                            ImageUrl = "vayes-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2020),
                            Name = "Vayes",
                            Price = 100.0,
                            Url = "vayes-egitim-kurumu"
                        },
                        new
                        {
                            Id = 10,
                            About = "bu bir Cybersecurity egitim firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2053),
                            FoundationYear = 1975,
                            ImageUrl = "cremicro-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2053),
                            Name = "Cremıcro",
                            Price = 355.0,
                            Url = "cremicro-egitim-kurumu"
                        },
                        new
                        {
                            Id = 11,
                            About = "bu bir Tasarım ve Marka oluşturma firmasıdır",
                            CategoryId = 0,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2057),
                            FoundationYear = 2005,
                            ImageUrl = "galta-media-egitim-kurumu",
                            IsActive = false,
                            IsDeleted = false,
                            LessonId = 19,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(2057),
                            Name = "galta media",
                            Price = 150.0,
                            Url = "galta-media-egitim-kurumu"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CategoriesLessons", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgenciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId", "CategoryId");

                    b.HasIndex("AgenciesId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoriesLessons");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            LessonId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            LessonId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            LessonId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            LessonId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            LessonId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            LessonId = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            LessonId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            LessonId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            LessonId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            LessonId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            LessonId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            LessonId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            LessonId = 20,
                            CategoryId = 5
                        },
                        new
                        {
                            LessonId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            LessonId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            LessonId = 4,
                            CategoryId = 6
                        },
                        new
                        {
                            LessonId = 8,
                            CategoryId = 6
                        },
                        new
                        {
                            LessonId = 13,
                            CategoryId = 6
                        },
                        new
                        {
                            LessonId = 17,
                            CategoryId = 7
                        },
                        new
                        {
                            LessonId = 18,
                            CategoryId = 7
                        },
                        new
                        {
                            LessonId = 7,
                            CategoryId = 8
                        },
                        new
                        {
                            LessonId = 5,
                            CategoryId = 8
                        },
                        new
                        {
                            LessonId = 9,
                            CategoryId = 8
                        },
                        new
                        {
                            LessonId = 9,
                            CategoryId = 9
                        },
                        new
                        {
                            LessonId = 10,
                            CategoryId = 9
                        },
                        new
                        {
                            LessonId = 11,
                            CategoryId = 9
                        },
                        new
                        {
                            LessonId = 12,
                            CategoryId = 9
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgenciesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Burada frontend egitimleri veriliyor",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4857),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4862),
                            Name = "frontend",
                            Url = "frontend-ile-ilgili-egitim"
                        },
                        new
                        {
                            Id = 2,
                            About = "Burada backend  egitimleri veriliyor",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4867),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4868),
                            Name = "Backend Egitimi",
                            Url = "backend-ile-ilgili-egitim"
                        },
                        new
                        {
                            Id = 3,
                            About = "Burada veritabanı Egitimleri veriliyor",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4871),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4872),
                            Name = "Veritabanı Egitimi",
                            Url = "veri-tabanı-ile-ilgili-egitim"
                        },
                        new
                        {
                            Id = 4,
                            About = "Burada veritabanlı  egitimleri veriliyor.",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4874),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4875),
                            Name = "Bulut bilişimler ve ios",
                            Url = "bulut-bilisimler-ve-ios-ile-egitim"
                        },
                        new
                        {
                            Id = 5,
                            About = "Burada Android programların egitimi verilecek",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4877),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4877),
                            Name = "Web App",
                            Url = "web-app-ile-egitim"
                        },
                        new
                        {
                            Id = 6,
                            About = "Burada Veri analizi ve ios programlama egitimleri veriliyor",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4880),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4880),
                            Name = "Oyun ve Android Programlama",
                            Url = "oyun-ve-android-programlama-ile-egitim"
                        },
                        new
                        {
                            Id = 7,
                            About = "Seo optimazsonu ve reklam tekniklerini ögreten ve logo oluşturmayı ögreten bir firma",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4882),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4883),
                            Name = "Reklam ve Pazarlama",
                            Url = "reklam-pazarlama-ile-egitim"
                        },
                        new
                        {
                            Id = 8,
                            About = "Burada dotnet egitimleri verilecek",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4885),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4886),
                            Name = ".Net Egitimi",
                            Url = "dotnet--ile-egitim"
                        },
                        new
                        {
                            Id = 9,
                            About = "Burada güvenlik egitimleri verilecek",
                            AgenciesId = 0,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4888),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 887, DateTimeKind.Local).AddTicks(4888),
                            Name = "CyberSecurity",
                            Url = "cyber-security-ile-egitim"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgenciesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodOfStudy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgenciesId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Full stack developer olarak çalışan uzmanlar, yazılımların back-end (arka katman) ve front-end(ön katman) olarak nitelendirilen bölümlerinde rol almaktadırlar. Aynı zamanda veritabanı programlama alanlarında yetkinlikleri olup, geliştirilmekte olan projenin yazılımla ilgili bütün aşamalarında görev almaktadırlar. Full Stack Development, HTML, CSS, JavaScript, ReactJS, Node.JS gibi birçok dil barındırmaktadır. Doğası gereği geniş ilgi alanına sahip bir disiplindir. Back-End’den Front-End’e ve veritabanlarına kadar uzanan bu yetkinlik Türkiye’de en çok aranan yazılım programlama dallarından biridir.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4496),
                            ImageUrl = "full-stack-web-application.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4500),
                            Name = "Full Stack Web Application",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "full-stack-web-application.jpg"
                        },
                        new
                        {
                            Id = 2,
                            About = "Bilişim sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde hızlı ve dinamik web uygulamaları geliştirmek, Python programlama dilinin artılarından yararlanmak için alabileceğiniz bu eğitim ile sıfırdan ileri seviyeye web geliştirici olma imkanını yakalayın.\r\n\r\n\r\n\r\nSektör tecrübesi yüksek uzman eğiticiler tarafından yapılacak online eğitimde katılımcılar alacakları teorik bilginin yanında edinecekleri uygulama deneyimi ile özelleştirilmiş ve hedefe yönelik bir eğitim alırlar.\r\n\r\n",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4510),
                            ImageUrl = "python-ile-web-gelistirme.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4511),
                            Name = "Python ile Web Geliştirme",
                            PeriodOfStudy = "85 saat",
                            Price = 30.000m,
                            Url = "python-ile-web-gelistirme"
                        },
                        new
                        {
                            Id = 3,
                            About = "Bilişim sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde, katılımcıların dünyanın en popüler ve güçlü programlama dillerinden Java'yı tanımaları ve uygulama geliştirecek seviyeye gelmeleri amaçlanmaktadır. Java Eğitiminde, veritabanı yönetimi ve programlanması MySql ilişkisel veritabanı yönetim sistemi ile gerçekleştirilir.\r\n\r\n \r\n\r\nBu eğitimi alan katılımcılar, ayrıca Java programlama dili ile beraber, kodlaması yapılmış bir uygulamada MySql veritabanına JDBC gibi erişim teknikleriyle nasıl bağlanılacağını, veritabanı üzerinde nasıl işlem gerçekleştirilebileceğini çeşitli uygulamalarla öğrenirler.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4514),
                            ImageUrl = "java-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4515),
                            Name = "Java Eğitimi (SE)",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "java-ile-egitim"
                        },
                        new
                        {
                            Id = 4,
                            About = "Bilişim sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde hızlı ve dinamik web uygulamaları geliştirmek, Python programlama dilinin artılarından yararlanmak için alabileceğiniz bu eğitim ile sıfırdan ileri seviyeye oyun geliştirici olma imkanını yakalayın.\r\n\r\n\r\n\r\nSektör tecrübesi yüksek uzman eğiticiler tarafından yapılacak online eğitimde katılımcılar alacakları teorik bilginin yanında edinecekleri uygulama deneyimi ile özelleştirilmiş ve hedefe yönelik bir eğitim alırlar.\r\n\r\n",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4518),
                            ImageUrl = "oyun-programlama-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4518),
                            Name = "Oyun Programlama",
                            PeriodOfStudy = "600 SAAT ",
                            Price = 70.000m,
                            Url = "oyun-programlama"
                        },
                        new
                        {
                            Id = 5,
                            About = "Bilişim sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde katılımcıların, PHP ile web yazılıma giriş yapmaları sağlanır ayrıca nesne yönelimli programlamayı (OOP) etkin bir biçimde kullanarak katmanlı yapıdaki proje mimarisi ile birlikte servis alt yapısının da kullanıldığı modüler web projeleri geliştirilmeleri sağlanır.\r\n\r\n \r\n\r\nServer side yazılım dillerinden olan PHP öğrenmek günümüzde popüler olan ve nitelikli uzman eleman açığı bulunan Wordpress, Laravel gibi frameworkler için ciddi bir temel oluşturacaktır.\r\n\r\n \r\n\r\nBir web sitesinin sıfırdan nasıl oluşturulduğunu, MySQL veritabanı bağlantısının nasıl kurulduğunu, veritabanı sorgulamalarını, etkili ve işlevsel bir websitesi hazırlamanın inceliklerini bu eğitimde öğrenebilirsiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4522),
                            ImageUrl = "php-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4522),
                            Name = "Php Eğitimi",
                            PeriodOfStudy = "72  saat",
                            Price = 70.000m,
                            Url = "php-ile-egitim"
                        },
                        new
                        {
                            Id = 6,
                            About = "Bilişim sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde hedefimiz Sql Server Management Studio üzerinde az da olsa bilgi sahibi olan katılımcıların temel Sql bilgilerini arttırdıktan sonra trigger ve procedure gibi sektörde sık karşılaşacakları veritabanı nesneleri üzerinde çalışabilmelerini sağlamaktır.\r\n\r\n \r\n\r\nİkinci bölümde ise yazılımcının veritabanı bağımlılığını azaltan ve aynı zamanda bir ORM aracı olan Entity Framework Code First ile veritabanı tasarımı performans konusu ile birlikte güncel örnekler üzerinden anlatılır.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4525),
                            ImageUrl = "entity-frameworkcore-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4526),
                            Name = "Entity Framework Eğitimi",
                            PeriodOfStudy = "65 saat",
                            Price = 70.000m,
                            Url = "entity-framework-ile-egitim"
                        },
                        new
                        {
                            Id = 7,
                            About = "Bilişim  sektöründe yer almayı hedefleyen öğrenci ve mezunlar, bu dilde kendisini geliştirip uzmanlaşmak isteyen ve kariyerini bilişim sektöründe ilerletmek isteyenlerin tercih edebileceği bu eğitimde, katılımcılara .Net 4.6 teknolojisi ile C# diline giriş yaparak temel ilkelerin öğretilmesi amaçlanmıştır. Bu eğitim ile katılımcılar modüler programlamanın alt yapısını oluşturan Nesne Yönelimli Programlama (OOP) ile birlikte windows ortamında çalışan uygulamalar yaparak Microsoft Visual Studio ile yazılım geliştirici olma yolunda ilk adımı atarlar.\r\n\r\n \r\n\r\nC# nedir sorusuna gelirsek; Microsoft tarafından Visual Studio.Net ile birlikte geliştirilen, bu platformun tüm özelliklerinden yararlanmanızı sağlayan nesne tabanlı bir programlama dilidir. Öğrenilmesi  kolay, esnek, güvenli, çok yönlü ve modern bir yapıya sahiptir. C# ile birbirinden farklı yazılım programları kolayca kodlanabilmektedir.\r\n\r\n \r\n\r\nGünümüzde yazılım uygulamaları veritabanından bağımsız düşünülemez. Bu eğitim ile Microsoft'un veritabanı yönetimi için geliştirmiş olduğu Microsoft Sql Server Management Studio ile veritabanı yönetiminin incelikleri öğretilir. Program sonunda veritabanı ile entegre işlemler yapabilen ve windows ortamında çalışan uygulamalar geliştirebilirsiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4529),
                            ImageUrl = "c-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4529),
                            Name = "C# Eğitimi",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "c#-ile-egitim"
                        },
                        new
                        {
                            Id = 8,
                            About = "Mobil uygulama geliştirme, kişisel dijital yardımcıları, kurumsal dijital yardımcıları veya cep telefonlarını içerebilen bir veya daha fazla mobil cihaz için bir mobil uygulamanın geliştirildiği eylem veya süreçtir.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4533),
                            ImageUrl = "mobil-uygulama-gelistirme-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4533),
                            Name = "Mobil Uygulama Geliştirme",
                            PeriodOfStudy = "115 saat",
                            Price = 70.000m,
                            Url = "mobil-uygulama-geliştirme-ile-egitim"
                        },
                        new
                        {
                            Id = 9,
                            About = "Bahçeşehir Üniversitesi | Wissen, Microsoft Gold Partner’i olarak Siber Güvenlik Uzmanlığı alanındaki eğitimlerini ileri seviye laboratuvarları ve uzman eğiticileri ile beraber gerçekleştirmektedir.Eğitim programımız başlamadan, kuralları bildiğinize ve kurallara uyacağınıza dair “Taahhütname” imzalamanız gerekmektedir.Doğru eğitim programını seçtiğinizden emin olunuz. Eğitim programlarımıza devamlılık zorunludur. Kurumun kabul edebileceği mazeretiniz olur ise Eğitim programlarının süresinin 1/10′ unu aşmamak üzere mazeret izni kullanabilirsiniz. Bu sürenin aşımı halinde, kursla ilişiğiniz kesilir.Eğitim programının başlangıcı itibariyle SGK, BAĞ-KUR veya Emekli Sandığı’ na bağlı olarak çalışıyorsanız eğitim programımıza katılamazsınız.Devam ettiğiniz her bir gün için 212.67 TL almaya hak kazanırsınız.Devam etmediğiniz günler için ödeme yapılmaz. Ödemeler açılacak banka hesabınıza aylık olarak yatırılır.İşsizlik sigortasından yararlanmakta iseniz kursa katılmanız halinde işsizlik sigortası ödemesi kesilmez (hak ettiğiniz kadar işsizlik ödeneğini ve kursa katıldığınız her gün için 212.67 TL‘yi almaya devam edersiniz).İşsizlik sigortasından yararlanmakta iken, geçerli bir gerekçe sunmadan katıldığınız kursu bırakmanız halinde bu tarihten itibaren işsizlik ödeneğiniz kesilir.Eğitim programı boyunca, ”Eğitim Maliyetleriniz” ile “İş Kazası ve Meslek Hastalığı Sigorta Priminiz” İŞKUR tarafından karşılanır.Eğitim aldığı programın uluslararası vendor sertifika sınavına bir defalığına ücretsiz katılım hakkı verilecektir.Eğitim aldığı programın uluslararası kitap ve materyali bir defalığına ücretsiz olarak verilecektir.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4536),
                            ImageUrl = "cyber-security-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4537),
                            Name = "cyber security",
                            PeriodOfStudy = "600 saat",
                            Price = 70.000m,
                            Url = "cyber-security-ile-egitim"
                        },
                        new
                        {
                            Id = 10,
                            About = "Bu eğitim katılımcılar Cloud yönetim ve işlemlerini gerçekleştirmek için gerekli bilgi ve yetenekleri,kazandırmak içindir. Katılımcılar Cloud yönetim yazılım çözümleri, Cloud alt yapısının temelleri, raporlama ve charge-back, Provision Clouds şablonları, Cloud yönetimi, izleme ve iyileştirme metodları, Cloud Özellikleri, kimlik denetimi, dağıtım modelleri hakkında bilgi sahibi olurlar.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4541),
                            ImageUrl = "cyber-security-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4541),
                            Name = "CCNA Cloud Yönetimi Eğitimi",
                            PeriodOfStudy = "72 saat",
                            Price = 70.000m,
                            Url = "cloud-yönetimi-egitimi"
                        },
                        new
                        {
                            Id = 11,
                            About = " \r\n\r\nCCNP Route Switching sertifikası alan kişi, yerel ve geniş ağları planlama, kurma, doğrulama ve sorun tespit etme ve problemleri giderme yetkinliklerine sahip olduğunu ortaya koymaktadır.\r\n\r\nRouting eğitimi alanlar, routing protokolleri ile güvenli kurumsal yerel ve geniş alan ağlarını planlamayı, kurmayı, konfigüre etmeyi ve doğrulamayı öğrenmektedir. Switch eğitimleri ile kompleks kurumsal switching planlaması, konfigürasyonu ve kurulumun doğrulanması öğretilmektedir.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4544),
                            ImageUrl = "cyber-security-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4545),
                            Name = "CCNP Route & Switching Eğitimi",
                            PeriodOfStudy = "108 saat",
                            Price = 70.000m,
                            Url = "ccnp-ile-egitim"
                        },
                        new
                        {
                            Id = 12,
                            About = "Bu eğitim Cisco Router ve Cisco Security ürünleri üzerinde gerçek senaryolara dayalı güvenlik tekniklerinin kullanılması ve yapılandırılmasını kapsar. Bu eğitim sonunda katılımcılar temel network güvenlik kavramları, Router ve Switch güvenliği, Kimlik Doğrulama, Firewall servisleri, Remote Access, izinsiz girişler ve içerik güvenliği konularında bilgi ve deneyim sahibi olacaklardır.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4548),
                            ImageUrl = "cyber-security-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4548),
                            Name = "CCNA Security Eğitimi",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "ccna-ile-egitim"
                        },
                        new
                        {
                            Id = 13,
                            About = "Java İle Android programlama eğitiminin ana hedefi Android işletim sisteminde çalışabilecek uygulamaların Java dili kullanılarak geliştirilmesidir. Bu eğitimimizde Java programlama dilinin temelleri detaylarıyla anlatılarak Android Studio yardımıyla Android uygulama geliştirmesi yapabilmeniz hedeflenmektedir.\r\n\r\n\r\n\r\nJava ve Android yazılım eğitiminde başlangıç düzeyindeki bir kişinin dahi anlayabileceği bir anlatım ve plan takip edilir. Kodlama dili ve işletim sistemindeki (Java ile Android uygulama geliştirmek adına gerekli) tüm detaylar aktarılır.\r\n\r\nAşama aşama sürdürülen eğitimlerle; kullanılan programlar, araçlar, modüller, kullanılan kod yapıları, hata yakalama ve yazılım test etme süreçleri aktarılır ve böylece programın ilk aşamadan son aşamaya kadar tüm bölümlerinde tam denetim yapabilecek yetkinliğe ulaşılır.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4551),
                            ImageUrl = "java-ile-android-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4552),
                            Name = "Java ile Android Programlama",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "java-ile-android-egitim"
                        },
                        new
                        {
                            Id = 14,
                            About = "iOS işletim sistemi üzerinde çalışan mobil programların yazılmasında Swift programlama dili kullanılır. Bu programlama dili, zengin uygulama alanları kadar iş bulmayı kolaylaştırması açısından da yoğun ilgi görür. Açık kaynak olan Swift kodları, programcıların dikkatini çeker.\r\n\r\n \r\n\r\nSwift dersleri ve iOS programlama eğitimi ile mobil cihazlar için kodlama yapabilir, farklı alanlarda çalışabilirsiniz. Mobil programlama ile kendi firmanızın ihtiyacı olan spesifik bir uygulamayı ya da herkesin kullanabileceği genel bir programı kolayca geliştirebilirsiniz.\r\n\r\n \r\n\r\nSwift programlama dili, macOS, iOS, watchOS ve tvOS işletim sistemlerinde kullanılan sezgisel ve güçlü bir programlama dilidir. Kodlaması kolay ve keyifli bir dildir. Modern özellikler taşıyan Swift kodları, etkileşimli ve eğlenceli bir yapı sunar. Tasarımsal olarak güvenli bir yapıya sahip olan Swift kodu, oldukça hızlı çalışan programlar yazmaya olanak tanır.\r\n\r\n \r\n\r\nMobil programlama, küçük kablosuz cihazlar için kodlanan yazılımlardır. Bu programlar, yazıldıkları cihazlarda bulunan diğer bileşenleri kullanabilir. Örneğin; akıllı saat üzerinde çalışması düşünülen bir sağlık uygulaması, cihaz üzerinde bulunan sıcaklık sensörünü kullanabilir. Bu doğrultuda, mobil programlama dilleri; cihazda daha az yer tutan, daha az enerji harcayan ve hızlı çalışan kodları hedefleyerek geliştirilir.\r\n\r\n \r\n\r\nSwift programlama dili, jenerik yapısıyla güçlü ve kolay bir kullanım sunar. Protokol uzantıları sayesinde jenerik kodlar yazmak çok daha kolaylaşır. Swift, metodları, uzantıları ve protokolleri destekleyen bir yapıya sahiptir.\r\n\r\n \r\n\r\nSwift programlama dilini öğrenirken Swift oyun alanı (Swift playgrounds) iOS uygulamasında bulmacalar çözmek için gerçek Swift kodlarını kullanabilirsiniz. Böylece mobil programlamayı eğlenceli hale de getirebilirsiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4555),
                            ImageUrl = "Swift-ile-egitim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4556),
                            Name = "Swift ile iOS Mobil Programlama Eğitimi",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "swift-ile-egitim"
                        },
                        new
                        {
                            Id = 15,
                            About = "Modern zamanın petrolü olarak kabul edilen verinin yakalanması, güvenli olarak saklanması, depolanması, yönetilmesi, programlanması, analiz edilmesi ve raporlanması tüm işletmeler için çok önemli hale gelmiştir. Verinin artan hacmi, türü ve oluşma hızı nedeniyle geleneksel yöntemlere ek olarak yeni nesil veri tabanları ve bulut teknolojiler gibi farklı mecralarda çalışma ihtiyaçları doğmuştur. Bu bağlamda piyasada veri mühendisi, veri bilimcisi, veri analisti, raporlama uzmanı ve veri tabanı yöneticisi gibi roller her zamankinden daha fazla talep edilir olmuştur. Bu eğitimle veriyle ilgili tüm parçalara derinlemesine girilip hem geleneksel veri tabanlarına hem büyük veri sistemlerine hem de bulut tabanlı veri tabanlarına hakim olunması sağlanacak ve katılımcılara veri ile ilgili bütünsel bir uzmanlık kazandırılacaktır.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4559),
                            ImageUrl = "full-data-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4559),
                            Name = "Full Data Uzmanlık Eğitimi",
                            PeriodOfStudy = "400 saat",
                            Price = 70.000m,
                            Url = "full-data-ile-egitim"
                        },
                        new
                        {
                            Id = 16,
                            About = "Bulut bilişim, bilgi işlem hizmetlerinin (sunucu, depolama, veri tabanı, ağ, yazılım, analiz ve makine zekası dahil) internet -bulut- üzerinden sağlanarak daha hızlı inovasyon, esnek kaynaklar ve ekonomik ölçeklendirme sunulması anlamına gelir. Normalde yalnızca kullandığınız bulut hizmetleri için ödeme yaptığınızdan işletim maliyetlerinizi düşürebilir, altyapınızı daha verimli bir şekilde çalıştırabilir ve değişen iş gereksinimlerinize uygun şekilde ölçeklendirme yapabilirsiniz.\r\n\r\nGünümüzde birçok kurum bulut teknolojisini kullanır ve birçok uzman bu devrim niteliğindeki bilgi işlem eğiliminin konsepti ile ilgili geliştirmeler yapar. Bulut bilgi işlem, işletmelerin BT kaynaklarına bakış açısını önemli ölçüde değiştirdi. Kurumlar, maliyet, küresel ölçeklendirme, performans, hız ve verimlilik gibi avantajları nedeniyle bulut bilişim hizmetlerine oldukça ilgi duymaktadırlar.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4562),
                            ImageUrl = "bulut-ile-egitim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 15,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4562),
                            Name = "Bulut Bilişim Uzmanlık Eğitimi",
                            PeriodOfStudy = "165 saat",
                            Price = 70.000m,
                            Url = "bulut-ile-egitim"
                        },
                        new
                        {
                            Id = 17,
                            About = "İleri Düzey SEO Eğitimi ile web sitesi sahipleri için olmazsa olmaz olan Arama Motoru Optimizasyonu(SEO)' nun temellerini kazanmış olacaksınız.İleri düzey teknikler hakkında da bilgi sahibi olacaksınız. Böylece rakip internet siteleri arasından sıyrılarak bir web sitesini Google gibi arama motorlarında başarılı hale getirmenin yöntemlerini öğrenmiş olacaksınız. Seo uyumlu içerik üretimi konusunda bilgiler öğreneceksiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4565),
                            ImageUrl = "seo-ile-egitim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 6,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4566),
                            Name = "Arama Motoru Optimizasyonu (SEO) Eğitimi",
                            PeriodOfStudy = "35 saat",
                            Price = 27.000m,
                            Url = "seo-ile-egitim"
                        },
                        new
                        {
                            Id = 18,
                            About = "İleri Düzey SEO Eğitimi ile web sitesi sahipleri için olmazsa olmaz olan Arama Motoru Optimizasyonu(SEO)' nun temellerini kazanmış olacaksınız.İleri düzey teknikler hakkında da bilgi sahibi olacaksınız. Böylece rakip internet siteleri arasından sıyrılarak bir web sitesini Google gibi arama motorlarında başarılı hale getirmenin yöntemlerini öğrenmiş olacaksınız. Seo uyumlu içerik üretimi konusunda bilgiler öğreneceksiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4570),
                            ImageUrl = "logo-tasarımı-ile-egitim.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 6,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4570),
                            Name = "Logo Tasarımı",
                            PeriodOfStudy = "27 saat",
                            Price = 16.000m,
                            Url = "logo-tasarımı-ile-egitim"
                        },
                        new
                        {
                            Id = 19,
                            About = "İleri Düzey SEO Eğitimi ile web sitesi sahipleri için olmazsa olmaz olan Arama Motoru Optimizasyonu(SEO)' nun temellerini kazanmış olacaksınız.İleri düzey teknikler hakkında da bilgi sahibi olacaksınız. Böylece rakip internet siteleri arasından sıyrılarak bir web sitesini Google gibi arama motorlarında başarılı hale getirmenin yöntemlerini öğrenmiş olacaksınız. Seo uyumlu içerik üretimi konusunda bilgiler öğreneceksiniz.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4573),
                            ImageUrl = "html-css-js-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 12,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4574),
                            Name = "Html,Css,Js Eğitimi",
                            PeriodOfStudy = "65 saat",
                            Price = 55.000m,
                            Url = "html-css-js-ile-egitim"
                        },
                        new
                        {
                            Id = 20,
                            About = "Bu eğitimin amacı mevcut javascript programlama dili bilginizle nodejs kullanarak sıfırdan dinamik web uygulamalarını geliştirebilecek bilgi ve beceriyi kazandırmaktır.",
                            AgenciesId = 1,
                            CreatedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4577),
                            ImageUrl = "node-ile-egitim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Kontenjan = 12,
                            ModifiedDate = new DateTime(2023, 7, 10, 18, 46, 2, 888, DateTimeKind.Local).AddTicks(4577),
                            Name = "Node.js ile Web Programlama",
                            PeriodOfStudy = "65 saat",
                            Price = 55.000m,
                            Url = "node-ile-egitim"
                        });
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("HowManyOfExperince")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AgenciesCategory", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Agencies", null)
                        .WithMany()
                        .HasForeignKey("AgenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.CategoriesLessons", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Agencies", null)
                        .WithMany("CategoriesLessons")
                        .HasForeignKey("AgenciesId");

                    b.HasOne("ConsultancyApp.Entity.Concrete.Category", "Category")
                        .WithMany("CategoriesLessons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultancyApp.Entity.Concrete.Lesson", "Lesson")
                        .WithMany("CategoriesLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Lesson", b =>
                {
                    b.HasOne("ConsultancyApp.Entity.Concrete.Agencies", "Agency")
                        .WithMany("Lessons")
                        .HasForeignKey("AgenciesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Agencies", b =>
                {
                    b.Navigation("CategoriesLessons");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Category", b =>
                {
                    b.Navigation("CategoriesLessons");
                });

            modelBuilder.Entity("ConsultancyApp.Entity.Concrete.Lesson", b =>
                {
                    b.Navigation("CategoriesLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
