using EgitimApp.Entity.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EgitimApp.Data.Concrete.EfCore.Configs
{
    public class CourseConfig :IEntityTypeConfiguration<Course>
    {
        public void Configure(EntityTypeBuilder<Course> builder)
        {

            builder.HasKey(c => c.Id);
            builder.Property(c => c.Id).ValueGeneratedOnAdd();

            builder.Property(c => c.CreatedDate).IsRequired();
            builder.Property(c => c.ModifiedDate).IsRequired();
            builder.Property(c => c.IsActive).IsRequired();
            builder.Property(c => c.IsDeleted).IsRequired();
            builder.Property(c => c.CourseName).IsRequired();
            builder.Property(c => c.TotalCourseHour).IsRequired();
            builder.Property(c => c.TotalCourseMonthly).IsRequired();
            builder.Property(c => c.Price).IsRequired();
            builder.Property(c => c.StartTime).IsRequired();
            builder.Property(c => c.EndTime).IsRequired();
            builder.Property(c => c.About).IsRequired();
            builder.Property(c => c.LevelofEducation).IsRequired();
            builder.Property(c => c.EducationContents).IsRequired();
            builder.Property(c => c.LocationofEducation).IsRequired();
            builder.Property(c => c.AchievementsOfEducation).IsRequired();
            builder.Property(c => c.EducationOfEvaluation).IsRequired();
            builder.Property(c => c.Url).IsRequired();
            builder.Property(c => c.ImageUrl).IsRequired();


            builder.HasData(
                new Course
                {
                    Id = 1,
                    CourseName = ".NET (.NET Core, MVC, Web API)",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = ".net-core-mvc",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    ImageUrl = "1.jpg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationContents = "Yazılım dersi",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 1,
                    IsActive = true,


                }, new Course
                {
                    Id = 2,
                    CourseName = "Java (Spring, Java SE, Java EE)",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "java",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "2.jpg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 200,
                    TotalCourseMonthly = 6,
                    TrainerId = 2,
                    IsActive = true,
                }, new Course
                {
                    Id = 3,
                    CourseName = "Python",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "python",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    ImageUrl = "3.jpg",
                    EducationContents = "Yazılım dersi",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 3,
                    IsActive = true,
                }, new Course
                {
                    Id = 4,
                    CourseName = "JavaScript",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "javascript",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "4.jpeg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 4,
                    IsActive = true,
                }, new Course
                {
                    Id = 5,
                    CourseName = "C/C++",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "c/c++",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "5.jpg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 5,
                    IsActive = true,
                }, new Course
                {
                    Id = 6,
                    CourseName = "iOS & Android",
                    TotalCourseHour = 300,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "ios-android",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "6.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 6,
                    IsActive = true,
                }, new Course
                {
                    Id = 7,
                    CourseName = "React Native",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "react-native",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "7.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 7,
                    IsActive = true,
                }, new Course
                {
                    Id = 8,
                    CourseName = "Flutter",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "flutter",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "8.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 8,
                    IsActive = true,
                }, new Course
                {
                    Id = 9,
                    CourseName = "Ionic",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "ionic",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "9.jpg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 9,
                    IsActive = true,
                }, new Course
                {
                    Id = 10,
                    CourseName = "Unity",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "unity",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "10.jpeg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 300,
                    TotalCourseMonthly = 6,
                    TrainerId = 10,
                    IsActive = true,
                }, new Course
                {
                    Id = 11,
                    CourseName = "Unreal Engine",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "unreal-engine",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "11.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 11,
                    IsActive = true,
                }, new Course
                {
                    Id = 12,
                    CourseName = "GameMaker Studio",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "gamemaker-studio",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "12.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 12,
                    IsActive = true,
                }, new Course
                {
                    Id = 13,
                    CourseName = "Buildbox",
                    TotalCourseHour = 400,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "buildbox",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "13.jpeg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 4,
                    TrainerId = 13,
                    IsActive = true,
                }, new Course
                {
                    Id = 14,
                    CourseName = "PHP",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "php",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "14.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 14,
                    IsActive = true,
                }, new Course
                {
                    Id = 15,
                    CourseName = "React",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "react",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "15.jpeg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 3,
                    TrainerId = 8,
                    IsActive = true,
                }, new Course
                {
                    Id = 16,
                    CourseName = "Angular",
                    TotalCourseHour = 400,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "angular",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "16.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 4,
                    TrainerId = 9,
                    IsActive = true,
                }, new Course
                {
                    Id = 17,
                    CourseName = "Node.js",
                    TotalCourseHour = 400,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "nodejs",
                    StartTime = DateTime.Now,
                    EducationContents = "Yazılım dersi",
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    ImageUrl = "17.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 4,
                    TrainerId = 10,
                    IsActive = true,
                }, new Course
                {
                    Id = 18,
                    CourseName = "Microsoft SQL Server",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "microsoft-sql-server",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "18.jpg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 11,
                    IsActive = true,
                }, new Course
                {
                    Id = 19,
                    CourseName = "MySQL",
                    TotalCourseHour = 100,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "mysql",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "19.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 2,
                    TrainerId = 12,
                    IsActive = true,
                }, new Course
                {
                    Id = 20,
                    CourseName = "PostgreSQL",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "postgresql",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Medium",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "20.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Tamamlandı",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 13,
                    IsActive = true,
                }, new Course
                {
                    Id = 21,
                    CourseName = "SQLite",
                    TotalCourseHour = 300,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "sqlite",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "21.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Açılacak",
                    EducationOfEvaluation = 5,
                    Price = 300,
                    TotalCourseMonthly = 3,
                    TrainerId = 11,
                    IsActive = true,
                }, new Course
                {
                    Id = 22,
                    CourseName = "Oracle",
                    TotalCourseHour = 400,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "oracle",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "22.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 4,
                    TrainerId = 12,
                    IsActive = true,
                }, new Course
                {
                    Id = 23,
                    CourseName = "Docker",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "docker",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "23.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 2,
                    TrainerId = 13,
                    IsActive = true,
                }, new Course
                {
                    Id = 24,
                    CourseName = "Jenkins",
                    TotalCourseHour = 400,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "jenkins",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "24.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 400,
                    TotalCourseMonthly = 4,
                    TrainerId = 14,
                    IsActive = true,
                }, new Course
                {
                    Id = 25,
                    CourseName = "Ansible",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "ansible",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "25.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 8,
                    IsActive = true,
                }, new Course
                {
                    Id = 26,
                    CourseName = "Sonarcube",
                    TotalCourseHour = 200,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "sonarcube",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "26.jpeg",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma,Web Geliştirme",
                    EducationStatus = "Devam ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 9,
                    IsActive = true,
                }, new Course
                {
                    Id = 27,
                    CourseName = "AWS",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "aws",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "27.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 10,
                    IsActive = true,
                }, new Course
                {
                    Id = 28,
                    CourseName = "Azure",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "azure",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Senior",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "28.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 11,
                    IsActive = true,
                }, new Course
                {
                    Id = 29,
                    CourseName = "Serverless",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = ".net-core-mvc",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "29.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 700,
                    TotalCourseMonthly = 6,
                    TrainerId = 12,
                    IsActive = true,
                }, new Course
                {
                    Id = 30,
                    CourseName = "Cloud Storage",
                    TotalCourseHour = 600,
                    About = "Yazılım dersi, bilgisayar bilimlerinin önemli bir alanıdır ve öğrencilere temel bilgisayar programlama, algoritma oluşturma, veri yapıları, yazılım mühendisliği ve uygulama geliştirme konularında bilgi sağlar. Bu ders, öğrencilere problem çözme becerileri kazandırarak mantıksal düşünce ve analitik yeteneklerini geliştirir. Yazılım dersi aynı zamanda modern teknoloji dünyasında önemli bir role sahip olan yazılım süreçlerini, proje yönetimini ve test etme yöntemlerini de kapsar. Öğrenciler, çeşitli programlama dilleri ve yazılım araçlarını kullanarak uygulamalar geliştirerek pratik deneyim elde eder. Bu ders, gelecekteki teknoloji liderleri ve yazılım geliştiricileri için temel bir adımdır.",
                    Url = "cloud-storage",
                    StartTime = DateTime.Now,
                    EndTime = DateTime.Now,
                    LevelofEducation = "Easy",
                    EducationContents = "Yazılım dersi",
                    ImageUrl = "30.png",
                    LocationofEducation = "Barbaros Bulvarı Yıldız İş Hanı No: 9 Kat: 3 Beşiktaş - İstanbul",
                    AchievementsOfEducation = "Kod yazma",
                    EducationStatus = "Devam Ediyor",
                    EducationOfEvaluation = 5,
                    Price = 100,
                    TotalCourseMonthly = 6,
                    TrainerId = 12,
                    IsActive = true,
                }

                );
        }
    }
}
